"""empty message

Revision ID: 640827f85a06
Revises: 8678d5480c3b
Create Date: 2022-10-11 05:21:32.013159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640827f85a06'
down_revision = '8678d5480c3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'password',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    # ### end Alembic commands ###
